"""Canonical target vocabulary. These values never translate legacy statuses."""
from enum import StrEnum


class ObjectType(StrEnum):
    SIGNAL = 'SIGNAL'
    FACT = 'FACT'
    FINDING = 'FINDING'
    HYPOTHESIS = 'HYPOTHESIS'
    INTERPRETATION = 'INTERPRETATION'
    ECONOMIC_STORY = 'ECONOMIC_STORY'
    ECONOMIC_IMPACT = 'ECONOMIC_IMPACT'
    OPPORTUNITY_CANDIDATE = 'OPPORTUNITY_CANDIDATE'
    VALIDATED_OPPORTUNITY = 'VALIDATED_OPPORTUNITY'
    MANAGEMENT_DECISION = 'MANAGEMENT_DECISION'
    ACTION_PLAN = 'ACTION_PLAN'
    ACTION = 'ACTION'
    BENEFIT_RECORD = 'BENEFIT_RECORD'


class RelationshipType(StrEnum):
    SUPPORTS = 'SUPPORTS'
    CONTRADICTS = 'CONTRADICTS'
    QUANTIFIES = 'QUANTIFIES'
    CONTEXTUALISES = 'CONTEXTUALISES'
    EXPLAINS = 'EXPLAINS'
    TEMPORALLY_PRECEDES = 'TEMPORALLY_PRECEDES'
    CO_MOVES_WITH = 'CO_MOVES_WITH'
    MITIGATES = 'MITIGATES'
    POTENTIALLY_DRIVES = 'POTENTIALLY_DRIVES'
    SUPPORTED_DRIVER_OF = 'SUPPORTED_DRIVER_OF'
    CONSEQUENCE_OF = 'CONSEQUENCE_OF'
    AMPLIFIES = 'AMPLIFIES'
    SHARES_EFFECT_WITH = 'SHARES_EFFECT_WITH'


class EvidenceRole(StrEnum):
    CONDITION = 'CONDITION'
    DRIVER_CANDIDATE = 'DRIVER_CANDIDATE'
    CONSEQUENCE_CANDIDATE = 'CONSEQUENCE_CANDIDATE'
    SUPPORTING = 'SUPPORTING'
    CONTRADICTORY = 'CONTRADICTORY'
    QUANTIFICATION = 'QUANTIFICATION'
    SEGMENTATION = 'SEGMENTATION'
    TEMPORAL = 'TEMPORAL'
    CONTEXTUAL = 'CONTEXTUAL'
    MITIGATING = 'MITIGATING'


class SourceAuthority(StrEnum):
    SOURCE_DATA = 'SOURCE_DATA'
    SYSTEM_DERIVED = 'SYSTEM_DERIVED'
    MANAGEMENT_ASSERTION = 'MANAGEMENT_ASSERTION'
    HUMAN_FD_JUDGEMENT = 'HUMAN_FD_JUDGEMENT'
    EXTERNAL = 'EXTERNAL'
    LEGACY_UNCLASSIFIED = 'LEGACY_UNCLASSIFIED'


class ConfidenceLevel(StrEnum):
    VERY_LOW = 'VERY_LOW'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    VERY_HIGH = 'VERY_HIGH'
    NOT_ASSESSED = 'NOT_ASSESSED'


class AssessmentLevel(StrEnum):
    """Qualitative materiality dimensions, never a combined score."""
    VERY_LOW = 'VERY_LOW'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    VERY_HIGH = 'VERY_HIGH'
    NOT_ASSESSED = 'NOT_ASSESSED'


class OverlapType(StrEnum):
    SAME_EFFECT = 'SAME_EFFECT'
    PARTIAL_OVERLAP = 'PARTIAL_OVERLAP'
    PARENT_CHILD = 'PARENT_CHILD'
    INDEPENDENT = 'INDEPENDENT'
    UNKNOWN_OVERLAP = 'UNKNOWN_OVERLAP'


class ImpactType(StrEnum):
    OBSERVED_LOSS = 'OBSERVED_LOSS'
    RUN_RATE_LEAKAGE = 'RUN_RATE_LEAKAGE'
    CASH_TRAPPED = 'CASH_TRAPPED'
    AVOIDABLE_COST = 'AVOIDABLE_COST'
    CAPITAL_AT_RISK = 'CAPITAL_AT_RISK'
    FUTURE_EXPOSURE = 'FUTURE_EXPOSURE'
    VALUE_CREATION_POTENTIAL = 'VALUE_CREATION_POTENTIAL'
    REALISED_BENEFIT = 'REALISED_BENEFIT'


class ImpactBasis(StrEnum):
    RECURRING_PROFIT = 'RECURRING_PROFIT'
    ONE_OFF_PROFIT = 'ONE_OFF_PROFIT'
    CASH_RELEASE = 'CASH_RELEASE'
    BALANCE_SHEET_EXPOSURE = 'BALANCE_SHEET_EXPOSURE'
    FUTURE_RISK_EXPOSURE = 'FUTURE_RISK_EXPOSURE'
    REALISED_BENEFIT = 'REALISED_BENEFIT'
    NOT_ASSESSED = 'NOT_ASSESSED'


class FindingStatus(StrEnum):
    DETECTED = 'DETECTED'
    VALIDATED = 'VALIDATED'
    MATERIAL = 'MATERIAL'
    PROMOTED_TO_REASONING = 'PROMOTED_TO_REASONING'
    DISMISSED = 'DISMISSED'


class ExplanationStatus(StrEnum):
    GENERATED = 'GENERATED'
    TESTING = 'TESTING'
    SUPPORTED = 'SUPPORTED'
    PLAUSIBLE = 'PLAUSIBLE'
    UNRESOLVED = 'UNRESOLVED'
    CONTRADICTED = 'CONTRADICTED'


class StoryStatus(StrEnum):
    CANDIDATE = 'CANDIDATE'
    INVESTIGATING = 'INVESTIGATING'
    SUPPORTED = 'SUPPORTED'
    QUANTIFIED = 'QUANTIFIED'
    ACTIONABLE = 'ACTIONABLE'
    MONITORING = 'MONITORING'
    IMPROVING = 'IMPROVING'
    RESOLVED = 'RESOLVED'
    PERSISTENT = 'PERSISTENT'
    WORSENING = 'WORSENING'
    REJECTED = 'REJECTED'
    UNRESOLVED = 'UNRESOLVED'


class OpportunityStatus(StrEnum):
    CANDIDATE = 'CANDIDATE'
    INVESTIGATING = 'INVESTIGATING'
    VALIDATED = 'VALIDATED'
    PRIORITISED = 'PRIORITISED'
    DECISION_REQUIRED = 'DECISION_REQUIRED'
    APPROVED = 'APPROVED'
    DECLINED = 'DECLINED'
    NOT_VIABLE = 'NOT_VIABLE'
    EXPIRED = 'EXPIRED'
    SUPERSEDED = 'SUPERSEDED'


class ActionStatus(StrEnum):
    PROPOSED = 'PROPOSED'
    APPROVED = 'APPROVED'
    NOT_STARTED = 'NOT_STARTED'
    IN_PROGRESS = 'IN_PROGRESS'
    BLOCKED = 'BLOCKED'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
    DEFERRED = 'DEFERRED'
    FAILED = 'FAILED'
    SUPERSEDED = 'SUPERSEDED'


class BenefitStatus(StrEnum):
    EXPECTED = 'EXPECTED'
    OBSERVED = 'OBSERVED'
    ATTRIBUTION_TESTING = 'ATTRIBUTION_TESTING'
    ATTRIBUTED = 'ATTRIBUTED'
    PARTIALLY_ATTRIBUTED = 'PARTIALLY_ATTRIBUTED'
    UNRESOLVED = 'UNRESOLVED'
    NOT_ATTRIBUTABLE = 'NOT_ATTRIBUTABLE'
    SUSTAINED = 'SUSTAINED'
    DECAYING = 'DECAYING'


class LineageKind(StrEnum):
    SOURCE_FILE = 'SOURCE_FILE'
    DATASET = 'DATASET'
    DATASET_VERSION = 'DATASET_VERSION'
    CANONICAL_RECORD = 'CANONICAL_RECORD'
    ENTITY = 'ENTITY'
    PRIMITIVE_RESULT = 'PRIMITIVE_RESULT'
    DIAGNOSTIC = 'DIAGNOSTIC'
    ANALYTICAL_RUN = 'ANALYTICAL_RUN'
    DERIVED_ANCESTOR = 'DERIVED_ANCESTOR'
    CALCULATION_LINEAGE = 'CALCULATION_LINEAGE'
    DIAGNOSTIC_LINEAGE = 'DIAGNOSTIC_LINEAGE'
    EVIDENCE_BUNDLE = 'EVIDENCE_BUNDLE'


class AuditEventType(StrEnum):
    OBJECT_CREATED = 'OBJECT_CREATED'
    OBJECT_UPDATED = 'OBJECT_UPDATED'
    STATUS_CHANGED = 'STATUS_CHANGED'
    EVIDENCE_LINKED = 'EVIDENCE_LINKED'
    EVIDENCE_UNLINKED = 'EVIDENCE_UNLINKED'
    CONFIDENCE_CHANGED = 'CONFIDENCE_CHANGED'
    MATERIALITY_CHANGED = 'MATERIALITY_CHANGED'
    MANAGEMENT_ASSERTION_RECORDED = 'MANAGEMENT_ASSERTION_RECORDED'
    HUMAN_OVERRIDE_RECORDED = 'HUMAN_OVERRIDE_RECORDED'
    OBJECT_SUPERSEDED = 'OBJECT_SUPERSEDED'


class ActorType(StrEnum):
    SYSTEM = 'SYSTEM'
    HUMAN = 'HUMAN'
    MANAGEMENT = 'MANAGEMENT'
    MIGRATION = 'MIGRATION'
    UNKNOWN = 'UNKNOWN'
